name: MarsBased
description: "MarsBased is an application development company in Barcelona, highly specialized in Ruby on Rails."
url: "http://www.marsbased.com"
markdown: redcarpet
highlighter: true
permalink: /blog/:year/:month/:day/:title
exclude: [
  'Gemfile', 'Gemfile.lock', 'corporate-jekyll.sublime-project', '.bundle',
  'corporate-jekyll.sublime-workspace', 'vendor', 'README.md', 'Rakefile'
]
assets:
  js_compressor: uglifier
  css_compressor: yui
excerpt_separator: <!--more-->
paginate: 10
paginate_path: "blog/page:num"
baseurl: '/'
